import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel("BlinkIT Grocery Data.xlsx")
print("Dataset Loaded Successfully")

print("\n First 5 Rows")
print(df.head())
print("\n Last 5 Rows")
print(df.tail())
print("\n Shape")
print(df.shape)
print("\n Columns")
print(df.columns)
print("\n Dataset Summary")
print(df.info())
print("\n Statistical Summary")
print(df.describe())
print("\n Missing Values")
print(df.isnull().sum())
print("\n Duplicate Records")
print(df.duplicated().sum())
df.drop_duplicates(inplace=True)
print("\n Dataset Shape After Cleaning")
print(df.shape)

# Question-01 total sales
total_sales = df["Sales"].sum()
print("\n Total Sales")
print(total_sales)
plt.figure(figsize=(6,3))
plt.text(
  0.5,
  0.5,
  f"Total Sales\n{total_sales:.2f}",
  fontsize=18,
  ha="center",
  va="center",
)
plt.axis("off")
plt.title("Total sales generated by BlinkIT")


plt.savefig("Q1_Total_Sales.png", dpi=300)
plt.show()

# Question-02 top 10 item types by sales
item_sales = (
  df.groupby("Item Type")["Sales"]
  .sum()
  .sort_values(ascending=False)
  .head(10)
)
print("\n Top 10 Item Types")
print(item_sales)
plt.figure(figsize=(8,5))
item_sales.plot(
  kind="bar",
  width=0.7
)
plt.title("Top 10 Item  by Sales", fontsize=12)
plt.xlabel("Item Type", fontsize=10)
plt.ylabel("Sales", fontsize=10)
plt.xticks(rotation=30, fontsize=10)
plt.yticks(fontsize=8)
plt.tight_layout()
plt.savefig("Q2_Top_Item_Types.png", dpi=300)
plt.show()

# Question-03 outlet type by sales
outlet_sales = (
  df.groupby("Outlet Type")["Sales"]
  .sum()
  .sort_values(ascending=False)
)
print("\n Outlet Type Sales")
print(outlet_sales)
plt.figure(figsize=(8,5))
outlet_sales.plot(kind="bar")
plt.title("Sales by Outlet Type")
plt.xlabel("Outlet Type")
plt.ylabel("Sales")
plt.xticks(rotation=20)
plt.tight_layout()
plt.savefig("Q3_Outlet_Type_Sales.png")
plt.show()

# Question-04 Outlet location type
location_sales = (
  df.groupby("Outlet Location Type")["Sales"]
  .sum()
)
print("\n Sales by Outlet Location")
print(location_sales)
plt.figure(figsize=(5,5))
plt.pie(
  location_sales,
  labels=location_sales.index,
  autopct="%1.1f%%",
  startangle=90,
  radius=0.9,
  textprops={"fontsize":9}
)
plt.title("Sales by Outlet Location Type", fontsize=11)
plt.tight_layout()
plt.savefig("Q4_Outlet_location_Sales.png")
plt.show()

# Question-05 Outlet size
size_sales = (
  df.groupby("Outlet Size")["Sales"]
  .sum()
)
print("\n Sales by Outlet Size")
print(size_sales)
plt.figure(figsize=(5,5))
plt.pie(
  size_sales,
  labels=size_sales.index,
  autopct="%1.1f%%",
  startangle=90,
  radius=0.9,
  textprops={"fontsize":9}
)
plt.title("Sales by Outlet Size")
plt.tight_layout()
plt.savefig("Q5_Outlet_Size_Sales.png", dpi=300)
plt.show()
print("\n 5 QUESTIONS COMPLETED SUCCESSFULLY")
print("PNG Images Saved Successfully")

# Question-06 blinkit expansion over the years
outlet_year = (
    df["Outlet Establishment Year"]
    .value_counts()
    .sort_index()
)
print("\nOutlets Established Each Year")
print(outlet_year)
plt.figure(figsize=(10,5))
plt.plot(
    outlet_year.index,
    outlet_year.values,
    marker="o"
)
plt.title("Blinkit Expansion Over the Years")
plt.xlabel("Establishment Year")
plt.ylabel("Number of Outlets")
plt.grid(True)
plt.tight_layout()
plt.savefig("Q6_Blinkit_Expansion.png")
plt.show()

# Question-07 item fat content sales
df["Item Fat Content"] = (
    df["Item Fat Content"]
    .replace({
        "LF": "Low Fat",
        "low fat": "Low Fat",
        "Low fat": "Low Fat",
        "reg": "Regular",
        "regular": "Regular"
    })
)
fat_sales = (
    df.groupby("Item Fat Content")["Sales"]
    .sum()
    .sort_values(ascending=False)
)
print("\nSales by Item Fat Content")
print(fat_sales)
plt.figure(figsize=(7,5))
sns.barplot(
    x=fat_sales.index,
    y=fat_sales.values
)
plt.title("Sales by Item Fat Content")
plt.xlabel("Item Fat Content")
plt.ylabel("Sales")
plt.tight_layout()
plt.savefig("Q7_Item_Fat_Content.png")
plt.show()

# Question-08 item visibility vs sales
plt.figure(figsize=(8,5))
sns.scatterplot(
    data=df,
    x="Item Visibility",
    y="Sales"
)
plt.title("Item Visibility vs Sales")
plt.xlabel("Item Visibility")
plt.ylabel("Sales")
plt.tight_layout()
plt.savefig("Q8_Visibility_vs_Sales.png")
plt.show()

# Question-09 highest rated item types
rating = (
    df.groupby("Item Type")["Rating"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)
print("\nTop Rated Item Types")
print(rating)
plt.figure(figsize=(10,6))
plt.barh(
    rating.index,
    rating.values
)
plt.title("Top 10 Highest Rated Item Types")
plt.xlabel("Average Rating")
plt.ylabel("Item Type")
plt.tight_layout()
plt.savefig("Q9_Top_Rated_Item_Types.png")
plt.show()

# final output
print("\nTop 10 Item Types by Sales")
print(item_sales)
print("\nTop Rated Item Types")
print(rating)
print("\nTotal Sales:", total_sales)
print("\nAnalysis Completed Successfully")
print("All charts saved successfully as PNG images.")